apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }} 
  labels:
    app: {{ .Chart.Name }}
    service: {{ .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.container.port }} 
    name: http 
  selector:
    app: {{ .Chart.Name }}